"""create articles

Revision ID: 084907ba74ce
Revises: 3ac3803ca62b
Create Date: 2024-02-04 15:37:25.750042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084907ba74ce'
down_revision: Union[str, None] = '3ac3803ca62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('summary', sa.Text(), nullable=True),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_articles_date'),
                    'articles', ['date'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_date'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
