from enum import Enum


class EnumSettings(Enum):
    DATABASE_URL = 'DATABASE_URL'
    OPENAI_API_KEY = 'OPENAI_API_KEY'
    HUGGINGFACEHUB_API_TOKEN = 'HUGGINGFACEHUB_API_TOKEN'
    AI_MODEL = 'AI_MODEL'
    EXECUTE_SUMMARIZER = 'EXECUTE_SUMMARIZER'
